### ISSUE TITLE
Weather Details Don't Work

### ISSUE THREAD

**Issue by Jesse-Hufstetler** [derek1906/CoolClock#1]
The URL must be broken.

![image](https://user-images.githubusercontent.com/14170257/36205702-a00ab31c-115d-11e8-8a11-a6ca6a197dbb.png)

![image](https://user-images.githubusercontent.com/14170257/36205649-76237cbe-115d-11e8-893c-c54d14b954fc.png)
![image](https://user-images.githubusercontent.com/14170257/36205659-7e9f03d6-115d-11e8-834d-6ac3b759bb20.png)

**Comment by derek1906** [comment]
That URL is provided by the Yahoo Weather API so I do not have control over it. Feel free to suggest other weather APIs and I will consider using it instead of Yahoo Weather. Thanks!

**Comment by Jesse-Hufstetler** [comment]
@derek1906 the URL above was http://us.rd.yahoo.com/dailynews/rss/weather/Country__Country/*https://weather.yahoo.com/country/state/city-12776918/. If you add `.split('*')[1]` to the end of that js string it will return https://weather.yahoo.com/country/state/city-12776918/ which is a valid web address. Perhaps you could do that? I'm trying to avoid having to learn how to build and debug a chrome extension or I'd make a pull request 😃.

**Comment by derek1906** [comment]
The URL is actually valid and use to work fine. I would avoid tempering with the URL since they might return a URL in different formats in the future. This issue might be temporary, so I will wait for a while before making any changes.
